spring:
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USER_NAME}
    password: ${DB_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate.descriptor.sql: info
