spring:
  datasource:
    url: jdbc:mysql://localhost:3306/woorimap
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.descriptor.sql: debug
